##
## Copyright (c) 2022-2023 Geosiris.
## SPDX-License-Identifier: Apache-2.0
##
name: Energyml Package common pypi-test

on: [pull_request]

jobs:

  build:
    name: Build distribution
    runs-on: ubuntu-latest

    strategy:
      matrix:
        xsd-link: [
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.0.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.1.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.2.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.3.zip"
        ]
    steps:

      - name: Compute version env
        run: |
          export COMMON_VERSION=`echo {{ $matrix.xsd-link }} | sed -r 's/.*_v(.*).zip$/\1/g'`
          export COMMON_VERSION_UNDERSCORE=`echo {{ $matrix.xsd-link }} | sed -r 's/.*_v(.*).zip$/\1/g' | sed -r 's/\.//g'`
          
          # export variable to github env          
          echo "COMMON_VERSION=$COMMON_VERSION" >> $GITHUB_ENV
          echo "COMMON_VERSION_UNDERSCORE=$COMMON_VERSION_UNDERSCORE" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Download COMMON v2.3
        run : wget ${{ matrix.xsd-link }} -P ${{ github.workspace }}

      - name: Unzip COMMON v2.3
        run: 7z x ${GITHUB_WORKSPACE}/common*.zip -o${{ github.workspace }}/xsd/common/

      - name: Install dependencies
        uses: ./.github/actions/prepare-poetry
        with:
          python-version: 3.9

      - name: generate
        run: |
          poetry install
          poetry run xsdata generate -ss single-package -p gen.common.commonv2 --postponed-annotations xsd/common/*/xsd_schemas/
#          poetry run xsdata generate -ss namespaces -p gen --postponed-annotations ../xsd/common/*/xsd_schemas/
          poetry run rename_pkgs --common ${{ env.COMMON_VERSION }} --src gen -o energyml
          mv energyml src/

      - name: Update toml
        run: |
          sed -i 's/<PROJECT_NAME>/energyml-common'"${{ env.COMMON_VERSION_UNDERSCORE }}"'/g' src/pyproject.toml
          sed -i 's/#\s*<PROJECT_DEPS>//g' src/pyproject.toml
          sed -i 's/<PROJECT_NAME>/energyml-common'"${{ env.COMMON_VERSION_UNDERSCORE }}"'/g' README.md
          cp README.md src/
          cp LICENSE src/

      - name: build
        run: |
          cd src
          poetry install
          poetry build

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact-${{ env.COMMON_VERSION_UNDERSCORE }}
          path: src/dist/

  publish:
    name: Publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        xsd-link: [
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.0.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.1.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.2.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.3.zip"
        ]

    steps:
      - name: Compute version env
        run: |
          export COMMON_VERSION=`echo {{ $matrix.xsd-link }} | sed -r 's/.*_v(.*).zip$/\1/g'`
          export COMMON_VERSION_UNDERSCORE=`echo {{ $matrix.xsd-link }} | sed -r 's/.*_v(.*).zip$/\1/g' | sed -r 's/\.//g'`
          
          # export variable to github env          
          echo "COMMON_VERSION=${{ env.COMMON_VERSION }}" >> $GITHUB_ENV
          echo "COMMON_VERSION_UNDERSCORE=${{ env.COMMON_VERSION_UNDERSCORE }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Retrieve the code and GIT history so that poetry-dynamic-versioning knows which version to upload
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact-${{ env.COMMON_VERSION_UNDERSCORE }}
          path: src/dist/

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: Update toml
        run: |
          sed -i 's/<PROJECT_NAME>/energyml-common'"${{ env.COMMON_VERSION_UNDERSCORE }}"'/g' src/pyproject.toml
          sed -i 's/#\s*<PROJECT_DEPS>//g' src/pyproject.toml
          sed -i 's/<PROJECT_NAME>/energyml-common'"${{ env.COMMON_VERSION_UNDERSCORE }}"'/g' README.md
          cp README.md src/
          cp LICENSE src/

      - name: Upload to PyPI TEST
        run: |
          cd src
          poetry config repositories.test https://test.pypi.org/legacy/
          poetry config http-basic.test ${{ secrets.POETRY_PYPI_TOKEN_USERNAME }} ${{ secrets.POETRY_TEST_PYPI_TOKEN_PASSWORD }}
          poetry publish --repository test