##
## Copyright (c) 2022-2023 Geosiris.
## SPDX-License-Identifier: Apache-2.0
##
name: Energyml Package common pypi-test

on: [pull_request]

jobs:

  build:
    name: Build distribution
    runs-on: ubuntu-latest

    strategy:
      matrix:
        xsd-link: [
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.0.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.1.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.2.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.3.zip"
        ]
    steps:

      - name: Compute version env
        run: |
          export PKG_VERSION="$(echo ${{ matrix.xsd-link }} | sed -r 's/.*_v(.*).zip$/\1/g')"
          export PKG_VERSION_UNDERSCORE="$(echo ${{ matrix.xsd-link }} | sed -r 's/.*_v(.*).zip$/\1/g' | sed -r 's/\./_/g')"
          
          # export variable to github env          
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "PKG_VERSION_UNDERSCORE=$PKG_VERSION_UNDERSCORE" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install poetry
        uses: ./.github/actions/prepare-poetry
        with:
          python-version: 3.9

      - name: Generate python classes
        uses: ./.github/actions/xsdata-generation
        with:
          xsd-url: ${{ matrix.xsd-link }}
          pkg-name: common
          version-common: ${{ env.PKG_VERSION }}

      - name: Update toml
        run: |
          sed -i 's/<PROJECT_NAME>/energyml-common'"${{ env.PKG_VERSION_UNDERSCORE }}"'/g' src/pyproject.toml
          sed -i 's/<PROJECT_SRC_FOLDER>/energyml/g' src/pyproject.toml
          sed -i 's/#\s*<PROJECT_DEPS>//g' src/pyproject.toml
          sed -i 's/<PROJECT_NAME>/energyml-common'"${{ env.PKG_VERSION_UNDERSCORE }}"'/g' README.md
          cp README.md src/
          cp LICENSE src/
          ls -l src

      - name: build
        run: |
          cd src
          poetry install
          poetry build

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact-${{ env.PKG_VERSION_UNDERSCORE }}
          path: src/dist/

  publish:
    name: Publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        xsd-link: [
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.0.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.1.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.2.zip",
          "http://geosiris.com/wp-content/uploads/2022/09/common_v2.3.zip"
        ]

    steps:
      - name: Compute version env
        run: |
          export PKG_VERSION=`echo ${{ matrix.xsd-link }} | sed -r 's/.*_v(.*).zip$/\1/g'`
          export PKG_VERSION_UNDERSCORE=`echo ${{ matrix.xsd-link }} | sed -r 's/.*_v(.*).zip$/\1/g' | sed -r 's/\.//g'`
          
          # export variable to github env          
          echo "PKG_VERSION=${{ env.PKG_VERSION }}" >> $GITHUB_ENV
          echo "PKG_VERSION_UNDERSCORE=${{ env.PKG_VERSION_UNDERSCORE }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Retrieve the code and GIT history so that poetry-dynamic-versioning knows which version to upload
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact-${{ env.PKG_VERSION_UNDERSCORE }}
          path: src/dist/

      - name: Install poetry
        uses: ./.github/actions/prepare-poetry
        with:
          python-version: 3.9

#      - name: Update toml
#        run: |
#          sed -i 's/<PROJECT_NAME>/energyml-common'"${{ env.PKG_VERSION_UNDERSCORE }}"'/g' src/pyproject.toml
#          sed -i 's/<PROJECT_SRC_FOLDER>/energyml/g' src/pyproject.toml
#          sed -i 's/#\s*<PROJECT_DEPS>//g' src/pyproject.toml
#          sed -i 's/<PROJECT_NAME>/energyml-common'"${{ env.PKG_VERSION_UNDERSCORE }}"'/g' README.md
#          cp README.md src/
#          cp LICENSE src/
#          ls -l src

      - name: Upload to PyPI TEST
        run: |
          cd src
          poetry config repositories.test https://test.pypi.org/legacy/
          poetry config http-basic.test ${{ secrets.POETRY_PYPI_TOKEN_USERNAME }} ${{ secrets.POETRY_TEST_PYPI_TOKEN_PASSWORD }}
          poetry publish --repository test