##
## Copyright (c) 2022-2023 Geosiris.
## SPDX-License-Identifier: Apache-2.0
##
name: Energyml Package prodml v2.2

on:
  release:
    types: [created]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Download COMMON v2.3
        run : wget http://geosiris.com/wp-content/uploads/2022/09/common_v2.3.zip -P ${{ github.workspace }}
  
      - name: Unzip COMMON v2.3
        run: 7z x ${GITHUB_WORKSPACE}/common_v2.3.zip -o${{ github.workspace }}/xsd/common/
        
      - name: Download prodml v2.2
        run : wget http://geosiris.com/wp-content/uploads/2022/09/prodml_v2.2.zip -P ${{ github.workspace }}

      - name: Unzip prodml v2.2
        run: 7z x ${GITHUB_WORKSPACE}/prodml_v2.2.zip -o${{ github.workspace }}/xsd/prodml/

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: generate
        run: |
          poetry install
          poetry run xsdata generate -ss clusters -p prodml22 --postponed-annotations xsd/prodml/v2.2/xsd_schemas/ 
          mv prodml22 src/

      - name: Update toml
        run: |
          sed -i 's/<PROJECT_NAME>/prodml22/g' src/pyproject.toml
          sed -i 's/<PROJECT_NAME>/prodml22/g' README.md
          cp README.md src/
          cp LICENSE src/

      - name: build
        run: |
          cd src
          poetry install
          poetry build

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact
          path: src/dist/

  publish:
    name: Publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Retrieve the code and GIT history so that poetry-dynamic-versioning knows which version to upload
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact
          path: src/dist/

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: Update toml
        run: |
          sed -i 's/<PROJECT_NAME>/prodml22/g' src/pyproject.toml
          sed -i 's/<PROJECT_NAME>/prodml22/g' README.md
          cp README.md src/
          cp LICENSE src/

      - name: Upload to PyPI TEST
        run: |
          cd src
          poetry publish --username ${{ secrets.POETRY_PYPI_TOKEN_USERNAME}} --password ${{ secrets.POETRY_PYPI_TOKEN_PASSWORD}}