name: Energyml Package Resqml v2.0.1 pypi-test

on:
  release:
    types: [created]


jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Download COMMON v2.0
        run : wget http://geosiris.com/wp-content/uploads/2022/09/common_v2.0.zip -P ${{ github.workspace }}
  
      - name: Unzip COMMON v2.0
        run: 7z x ${GITHUB_WORKSPACE}/common_v2.0.zip -o${{ github.workspace }}/xsd/common/
        
      - name: Download RESQML v2.0.1
        run : wget http://geosiris.com/wp-content/uploads/2022/09/resqml_v2.0.1.zip -P ${{ github.workspace }}

      - name: Unzip RESQML v2.0.1
        run: 7z x ${GITHUB_WORKSPACE}/resqml_v2.0.1.zip -o${{ github.workspace }}/xsd/resqml/

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: generate
        run: |
          poetry install
          poetry run xsdata generate -ss namespace-clusters -p gen --postponed-annotations xsd/resqml/v2.0.1/xsd_schemas/ 
          poetry run rename_pkgs -c 2.0 -r 2.0.1 -s gen -o resqml201py
          mv resqml201py src/

      - name: Update toml
        run: |
          sed -i 's/<PROJECT_NAME>/resqml201py/g' src/pyproject.toml
          sed -i 's/<PROJECT_NAME>/resqml201py/g' README.md
          cp README.md src/
          cp LICENSE src/

      - name: build
        run: |
          cd src
          poetry install
          poetry build

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact
          path: src/dist/

  publish:
    name: Publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Retrieve the code and GIT history so that poetry-dynamic-versioning knows which version to upload
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact
          path: src/dist/

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: Update toml
        run: |
          sed -i 's/<PROJECT_NAME>/resqml201py/g' src/pyproject.toml
          sed -i 's/<PROJECT_NAME>/resqml201py/g' README.md
          cp README.md src/
          cp LICENSE src/

      - name: Upload to PyPI TEST
        run: |
          cd src
          poetry config repositories.test https://test.pypi.org/legacy/
          poetry config http-basic.test ${{ secrets.POETRY_PYPI_TOKEN_USERNAME}} ${{ secrets.POETRY_TEST_PYPI_TOKEN_PASSWORD}}
          poetry publish --repository test
