name: Energyml Package witsml v2.1 pypi-test

on: [push,pull_request]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Download COMMON v2.3
        run : wget http://geosiris.com/wp-content/uploads/2022/09/common_v2.3.zip -P ${{ github.workspace }}
  
      - name: Unzip COMMON v2.3
        run: 7z x ${GITHUB_WORKSPACE}/common_v2.3.zip -o${{ github.workspace }}/xsd/common/
        
      - name: Download witsml v2.1
        run : wget http://geosiris.com/wp-content/uploads/2022/09/witsml_v2.1.zip -P ${{ github.workspace }}

      - name: Unzip witsml v2.1
        run: 7z x ${GITHUB_WORKSPACE}/witsml_v2.1.zip -o${{ github.workspace }}/xsd/witsml/

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: generate
        run: |
          poetry install
          poetry run xsdata generate -ss namespace-clusters -p gen --postponed-annotations xsd/witsml/v2.1/xsd_schemas/ 
          poetry run rename_pkgs -c 2.3 -w 2.1 -s gen -o energyml-witsml21/energyml
          mv energyml-witsml21 src/

      - name: copy readme and license
        cp README.md src/
        cp LICENSE src/

      - name: build
        run: |
          sed -i 's/<PROJECT_NAME>/energyml-witsml21/g' src/pyproject.toml
          cd src
          poetry install
          poetry build

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact
          path: src/dist/

  publish:
    name: Publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Retrieve the code and GIT history so that poetry-dynamic-versioning knows which version to upload
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact
          path: dist/

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: Update toml
        run: |
          sed -i 's/<PROJECT_NAME>/name = "energyml-witsml21"/g' src/pyproject.toml

      - name: Upload to PyPI TEST
        run: |
          cd src
          poetry config repositories.test https://test.pypi.org/legacy/
          poetry config http-basic.test ${{ secrets.POETRY_PYPI_TOKEN_USERNAME}} ${{ secrets.POETRY_TEST_PYPI_TOKEN_PASSWORD}}
          poetry publish --repository test
